### ISSUE TITLE
pcc_3e/chapter_11 /test_name_function.py differs from text printed in book

### ISSUE THREAD

**Issue by therealdjango** [ehmatthes/pcc_3e#10]
The code in the German book version (2023) actually differs from the code provided on GitHub leading to an error when trying pytest Maybe in the next edition of the book the code can be synchronized.

By the way, the book is great and helps a lot even for intermediate python programmers. Thanks a lot!

Error in Anaconda Prompt:
E       fixture 'self' not found

Code in  German book:
<img width="381" alt="image" src="https://github.com/ehmatthes/pcc_3e/assets/162823763/203fbfa1-86f7-476b-a18a-dc78c10ec98b">

**Comment by ehmatthes** [comment]
Hi @therealdjango. The code you shared matches the [second edition](https://github.com/ehmatthes/pcc_2e/blob/master/chapter_11/test_name_function.py) of the book. Are you sure you have a copy of the third edition?

**Comment by therealdjango** [comment]
Hi @ehmatthes,
yes I just double-checked. It's the German version from 2023 / 3. Edition.

**Comment by ehmatthes** [comment]
Would you mind emailing me? I'm ehmatthes at gmail. If that doesn't work, I can carry on the conversation here.
