### ISSUE TITLE
Matplotlib installation through pip

### ISSUE THREAD

**Issue by saxena-codes** [ehmatthes/pcc_3e#9]
## Issue:

Error while running `python mpl_squares.py` at Page 302 on raspberry pi.
Following error: `ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory`

Found this reference:
https://numpy.org/devdocs/user/troubleshooting-importerror.html#raspberry-pi

Tried both the options mentioned in above reference, none worked. Please guide.

**Comment by saxena-codes** [comment]
This worked for me:

```
sudo apt remove python3-numpy
pip uninstall numpy
pip install numpy==1.21
```

It seems matplotlib only work with NumPy 1.21 version. Don't know why NumPy 1.26 is not working with matplotlib.

@ehmatthes Can be mentioned in the book/ references for other users.

Regards,

**Comment by ehmatthes** [comment]
I'm glad you got that sorted for your specific raspberry pi. I can't include notes in the book about compatibility issues on every platform like this.
